apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drkiq
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: drkiq
    spec: 
      containers:
      - name: drkiq
        image: drkiq:v1
        ports:
        - containerPort: 8000
          name: drkiq-port
        volumeMounts:
        - mountPath: /drkiq
          name: drkiq-vol
        envFrom:
        - configMapRef:
            name: drkiq-config
      volumes:
      - name: drkiq-vol
        hostPath:
          path: /c/Users/vip/drkiq
          type: Directory
