apiVersion: v1
kind: Service
metadata:
  name: drkiq
  labels:
    svc: drkiq
spec:
  type: NodePort
  ports:
  - name: drkiq-port
    port: 8000
    nodePort: 30001
    protocol: TCP
  selector:
    app: drkiq
