apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec: 
      containers:
      - name: redis
        image: redis:3.0.5
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: drkiq-redis	
      volumes:
      - name: drkiq-redis
        persistentVolumeClaim:
          claimName: drkiq-redis